---
title: ''
---

```{r}
#| label: load-packages
#| include: false

library(tidyverse)
library(palmerpenguins)
```

# COMM 7018: Social Media Theory

[Fitchburg State University](https://fitchburgstate.edu)\
[Communications Media Department](https://www.fitchburgstate.edu/academics/academic-schools/school-arts-and-sciences/communications-media-department)\
[MS in Applied Communication: Social Media Concentration](https://www.fitchburgstate.edu/academics/programs/social-media-concentration-applied-communication-ms-online)

GCE Online-Accelerated\  
7 weeks, Monday 22 May -- Sunday 9 July 2023\
Instructor: Dr. Martin Roberts\

------------------------------------------------------------------------

## Overview

The term **social media** is popularly understood as referring to corporate-owned, advertising-funded communication **platforms** based on **user-generated content**: YouTube, Instagram, Facebook, Twitter, Twitch, Discord, TikTok. It can also be defined more broadly, however, as a set of networked, technologically-mediated **practices** of communication, structured by economic and political forces that both inflect and are inflected by social and cultural identities. These platforms, the social practices that they enable, and the relationship between the two are the objects of **social media theory**. But what does it mean to **theorize** social media? Why do we need social media theory at all?

To theorize something involves a number of processes:

-   first, how do we define the phenomenon or object of study itself? How does it differ from previous or other related phenomena?
-   how are we to account for it? Why did it happen/is it happening now rather than at some other time? What are its conditions of possibility?
-   what is its relation to larger areas of society? What are its implications for those areas?
-   how are we to evaluate it, in terms of its implications (political, economic, social, ethical, legal, environmental, aesthetic)? What are its possibilities and limits, its progressive and oppressive aspects? How can we change it for the better?

These processes involve developing analytical frameworks or models comprising concepts that are useful for identifying and analyzing key aspects of and issues raised by the phenomenon/object in question. These frameworks and concepts typically draw from existing ones in different fields of study, but often involve the proposal of new frameworks and concepts specific to the field in question.

Each week of the course focuses on some of the key dimensions of social media communication:

-   the role of **language** in social media and its transformation;
-   the **aesthetic** dimension of social media communication and the centrality of the **image** as a unit of exchange on social media platforms;
-   the dimension of **sharing** that is arguably the central practice of social media;
-   the **affective** or emotionally-expresssive dimension of social media, i.e. their role in articulating and sharing **structures of feeling**;
-   critiques of the **surveillance capitalism** of commercial SM platforms and debates about their practices as a form of **techno-feudalism**;
-   the notion of social media as a complex **ecosystem** of interdependent practices, as well as proposals for addressing toxic elements within this ecosystem.

------------------------------------------------------------------------

## Objectives

By the end of the course, students will be able to:

-   analyze technologies past, present, and imagined
-   describe the ways in which technologies shape our world the ways in which we shape those technologies
-   explain how social media is a result of the intersection between technologies and existing human communication dynamics
-   discuss how theory of technology and social media can improve the vocational outlook of a student
-   play a productive role in and even facilitate conversations that tease out the relationships between values and technology.
-   through the skills you will refine in writing your research papers, clearly explain how a specific technology shapes the social world that we live in.

------------------------------------------------------------------------

## Sources: Print/Web

For reading, we will use ebooks, PDFs, and audiobooks.  

PDF documents and the syllabus will be available for download in the [Course Repository](https://github.com/mroberts1/social-mobilities-fall-22) hosted on GitHub: please bookmark this link. The <pdf> folder on the repo will have copies of assigned PDF chapters and articles; to download, click on the document in question and then the Download button. 

**Required**  

-   Amy Bruckman, *Should You Believe Wikipedia? Online Communities and the Construction of Knowledge*. Cambridge: Cambridge University Press, 2022.  

-   Claire Dederer, *Monsters: A Fan's Dilemma*. New York: Alfred A. Knopf, 2023.  

-   Byung-Chul Han, *In The Swarm: Digital Prospects*.                                                                                                                      Cambridge: MIT Press, 2017.

-   [Adrian Hon](https://mssv.net/), *You've Been Played: How Corporations, Governments, and Schools Use Games to Control Us All*. New York: Basic Books, 2022.

-   Allissa V. Richardson, *Bearing Witness While Black: African Americans, Smartphones, and the New Protest #Journalism*. Oxford: Oxford University Press, 2020.  

-   Nicholas A. John, *The Age of Sharing*. Cambridge: Polity Press, 2016.

Michele White, _Touch Screen Theory: Digital Devices and Feelings_. Cambridge, MA: MIT Press.   [Open Access](https://direct.mit.edu/books/oa-monograph/5462/Touch-Screen-TheoryDigital-Devices-and-Feelings)  


**Other sources**\
These sources are either available online or excerpts will be posted on Blackboard.

-   Noam Chomsky, 
-   Yves Citton, *The Ecology of Attention*. Cambridge: Polity Press, 2017 \[French edition: *Pour une écologie de l'attention*, Éditions du Seuil, 2014\].
-   Adam D.I. Kramer, Jamie E. Guillory, and Jeffrey T. Hancock, "[Experimental evidence of massive-scale emotional contagion through social networks](https://doi.org/10.1073/pnas.1320040111)," *PNAS*, vol. 111, no. 24 (17 June 2014): 8788-8790.
-   Lev Manovich, "The Aesthetic Society, or How I Edit My Instagram," in Peter Mörtenböck and Helge Mooshammer, eds., *Data Publics: Public Plurality in an Era of Data Determinacy* (New York: Routledge, 2020).
-   Gary Marcus & Ernest Davis, "Insights from the Human Mind" (chapter 6 of *Rebooting AI: Building Artificial Intelligence We Can Trust* (New York: Pantheon Books, 2019)).
-   Tony D. Sampson, Stephen Maddison, Darren Ellis, eds., *Affect and Social Media: Emotion, Media, Anxiety and Contagion*. London and New York: Rowman & Littlefield, 2018.
-   José van Dijck, *The Culture of Connectivity: A Critical History of Social Media*. Oxford: Oxford University Press, 2013.
-   [Evgeny Morozov](https://twitter.com/evgenymorozov), "[Critique of Techno-Feudal Reason](https://newleftreview.org/issues/ii133/articles/evgeny-morozov-critique-of-techno-feudal-reason)," *New Left Review*, 133/134 (Jan-Apr 2022).
-   Whitney Phillips and Ryan M. Milner, *You Are Here: A Field Guide for Navigating Polarized Speech, Conspiracy Theories, and Our Polluted Media Landscape* (Cambridge: MIT Press, 2021).
-   Alise Tifentale, "[Art of the Masses: From Kodak Brownie to Instagram](https://doi.org/10.31165/nk.2015.86.399.v)," *Networking Knowledge: Journal of the MeCCSA Postgraduate Network* 8 (6) (2015).
-   [Shoshana Zuboff](https://shoshanazuboff.com), "[You Are the Object of a Secret Extraction Operation](https://www.nytimes.com/2021/11/12/opinion/facebook-privacy.html)," *New York Times*, 12 Nov 2021.

------------------------------------------------------------------------

## Course Information

**Platforms**  
We’ll be using Blackboard for submitting assignments ONLY. For discussion, we will be using Discord.  

Please be sure to check in to the site at least once daily M-F to check the Announcements page and the Discussion forum for the week.

**Sources**  
For reading, we will use ebooks, PDFs, and audiobooks.  

PDF documents and the syllabus will be available for download in the Course Repository hosted on GitHub: please bookmark this link. The folder on the repo will have copies of assigned PDF chapters and articles; to download, click on the document in question and then the Download button.  

------------------------------------------------------------------------

## Weekly Schedule

**Week 1** M 05/16

Topic: Speaking/Writing

-   [Gretchen McCulloch](https://gretchenmcculloch.com/), *Because Internet*: "Informal Writing," "Typographical Tone of Voice," "Emoji and Other Internet Gestures" (chs. 1, 4, 5)

See also:

-   Geoffrey K. Pullum, "[Phrases for Lazy Writers in Kit Form](http://itre.cis.upenn.edu/%7Emyl/languagelog/archives/000061.html)," *Language Log*, 27 Oct. 2003
-   Glen Whitman, "[Phrases for Lazy Writers in Kit Form Are the New Clichés](http://agoraphilia.blogspot.com/2004/01/phrases-for-lazy-writers-in-kit-form.html)," *Agoraphilia*, 14 Jan. 2004
-   Geoffrey K. Pullum, "[Snowclones: Lexicological Dating to the Second](http://itre.cis.upenn.edu/~myl/languagelog/archives/000350.html)," *Language Log*, 16 Jan. 2004
-   Erin O'Connor, "[A bit of Language-Log-ish geekery](https://kirinqueen.livejournal.com/170517.html), *kirinqeen* blog, 23 June 2005
-   [The Snowclones Database](https://snowclones.org/about/)

------------------------------------------------------------------------

**Week 2** M 05/23

Topic: Aesthetics

-   [Alise Tifentale](https://www.alisetifentale.net/), "[Art of the Masses: From Kodak Brownie to Instagram](https://doi.org/10.31165/nk.2015.86.399.v),"
-   [Lev Manovich](https://manovich.net), "The Aesthetic Society, or How I Edit My Instagram"

------------------------------------------------------------------------

**Week 3** M 05/30

Topic: Sharing

-   José van Dijck, *The Culture of Connectivity*: "Facebook and the Imperative of Sharing" (ch. 3)
-   Nicholas John, *The Age of Sharing*: "Introduction," "Sharing and the Internet" (ch. 3)

------------------------------------------------------------------------

**Week 4** M 06/06

Topic: Affect

-   Nicholas John, *The Age of Sharing*: "Sharing our Feelings" (ch. 3)
-   Tony D. Sampson et al., *Affect and Social Media: Emotion, Media, Anxiety and Contagion*: "Introduction: On Affect, Social Media and Criticality"
-   Optional: Adam D.I. Kramer, et al., "[Experimental evidence of massive-scale emotional contagion through social networks](https://doi.org/10.1073/pnas.1320040111)," *PNAS*, vol. 111, no. 24 (17 June 2014): 8788-8790

------------------------------------------------------------------------

**Week 5** M 06/13

Topic: Disposession

-   [Shoshana Zuboff](https://shoshanazuboff.com), "[You Are the Object of a Secret Extraction Operation](https://www.nytimes.com/2021/11/12/opinion/facebook-privacy.html)"
-   [Evgeny Morozov](https://twitter.com/evgenymorozov), "Critique of Techno-Feudal Reason"

------------------------------------------------------------------------

**Week 6** M 06/20

Topic: Ecologies

-   Yves Citton, *The Ecology of Attention*: "Introduction: From Attention Economy to Attention Ecology"
-   Whitney Phillps and Ryan Milner, *You Are Here*: "Introduction: Mapping Network Pollution"

------------------------------------------------------------------------

**Week 7** M 06/27

Topic: Research paper presentations

------------------------------------------------------------------------

## Assignments & Evaluation

-   **Review**: 6, weekly from Week 1, one short post responding to readings, 250 words (maximum), due by Friday (20%)
-   **Discussion**: weekly after Week 1, 2-3 responses to other students' posts., 100 words max., due by the *following* Friday (20%)
-   **Commentary**: 2 short papers, 750-1000 words, due Friday of Week 2 and Week 4 (20%)
-   **Research paper/report/other project**: 2,000 words, due Friday of week 6 (20%)
-   **Colloquium**: week 7, flexible format - slides, video/audio, web page, blog, wiki (20%)

**Discussion: Agenda, Review, Reply Posts**\
For Weeks 1-6, each of the weekly topics will be active across a cycle of two weeks.

By the end of the day on **Monday** of each week, I will post an Agenda item in the Discussion forum for the topic of the week, that introduces and contextualizes the reading assignments for the week, identifying key themes, concepts, and/or issues to look out for as you read. Be sure to read the Agenda post before beginning the reading assignments.

In the first week, complete the reading assignments and make an initial response post called a Review, with question and/or comments on them, by **Friday** of the week in question.

In the second week, read through the Review posts of the group and post at least one Reply to one of them by Friday of that week.

**Commentary Papers**\
These short papers (750-1,000 words) are due at the end of Week 2 and Week 4 (Sunday). They should consist of close analytical readings of any of the reading assignments for the period Weeks 1-2 or 3-4. You are encouraged to focus in detail on particular sections, arguments, and/or concepts from the readings and develop them.

**Research Paper/Project**\
The culminating written assignment for the course (2,000 words) may consist of various formats: a research paper or report, or a creative project of your choice.

A 1-page preliminary proposal with ideas for your project, with a short bibliography with sources and/or links, should be posted in the Discussion forum for the purpose by the end of Week 3, and you will receive feedback during Week 4.

**Colloquium**\
Research papers/projects will be presented to and discussed with the group at the Colloquium scheduled over the last week of the course. Presentation formats are flexible, and may include a recorded slide presentation (20 slides max.) with voiceover; an audiovisual essay; or a web page, wiki, or blog.

------------------------------------------------------------------------

## Bibliography

\[A\] = Audiobook  

danah boyd, *It's Complicated: The Social Lives of Networked Teens* (New Haven: Yale University Press, 2014).

Amy Bruckman, *Should You Believe Wikipedia? Online Communities and the Construction of Knowledge* (Cambridge: Cambridge University Press, 2022).  

Claire Dederer, *Monsters: A Fan's Dilemma* (New York: Alfred A. Knopf, 2023).    

Finn Brunton and Helen Nissenbaum, *Obfuscation: A User's Guide for Privacy and Protest* (Cambridge: MIT Press, 2016).

Gabriella Coleman, *Hacker, Hoaxer, Whistleblower, Spy: The Many Faces of Anonymous* (London and New York: Verso, 2014).

David Craig, Jian Lin, and Stuart Cunningham, *Wanghong as Social Media Entertainment in China*. Palgrave Studies in Globalization, Culture and Society (London: Palgrave, 2021).

Stuart Cunningham and David Craig, *Social Media Entertainment: The New Intersection of Hollywood and Silicon Valley* (New York: NYU Press, 2021).

---, eds. *Creator Culture: An Introduction to Global Social Media Entertainment* (New York: New York University Press, 2021).

Byung-Chul Han, *In The Swarm: Digital Prospects* (Cambridge: MIT Press, 2017).

\[A\] [Adrian Hon](https://mssv.net/), *You've Been Played: How Corporations, Governments, and Schools Use Games to Control Us All* (New York: Basic Books, 2022).  

Sarah J. Jackson, Moya Bailey, et al., *#Hashtag Activism: Networks of Race and Gender Justice* (Cambridge: MIT Press, 2020).

Lev Manovich, *Instagram and Contemporary Image* (2015-17).

\[A\] Gretchen McCulloch, *Because Internet: Understanding the New Rules of Language* (New York: Riverhead Books, 2019).

Angela Nagle, *Kill All Normies: Online Culture Wars From 4Chan and Tumblr to Trump and the Alt-Right* (Alresford, Hampshire, UK: Zero Books, 2017).

Whitney Phillips, *This Is Why We Can't Have Nice Things: Mapping the Relationship between Online Trolling and Mainstream Culture* (Cambridge: MIT Press, 2015).

Whitney Phillips and Ryan M. Milner, *You Are Here: A Field Guide for Navigating Polarized Speech, Conspiracy Theories, and Our Polluted Media Landscape* (Cambridge: MIT Press, 2021).

Allissa V. Richardson, *Bearing Witness While Black: African Americans, Smartphones, and the New Protest #Journalism* (Oxford: Oxford University Press, 2020).

Kai Strittmatter, *We Have Been Harmonized: Life in China's Surveillance State* (New York: HarperCollins, 2020).

Zeynep Tufekci, *Twitter and Tear Gas: The Power and Fragility of Networked Protest* (New Haven: Yale University Press, 2017).

Michele White, _Touch Screen Theory: Digital Devices and Feelings_ (Cambridge, MA: MIT Press, 2022).   [Open Access](https://direct.mit.edu/books/oa-monograph/5462/Touch-Screen-TheoryDigital-Devices-and-Feelings)  


------------------------------------------------------------------------

## Late Policy

Assignments that are late will lose 1/2 of a grade per day, beginning at the end of class and including weekends and holidays. This means that a paper, which would have received an A if it was on time, will receive a B+ the next day, B- for two days late, and so on. Time management, preparation for our meetings, and timely submission of your work comprise a significant dimension of your professionalism. As such, your work must be completed by the beginning of class on the day it is due. If you have a serious problem that makes punctual submission impossible, you must discuss this matter with me before the due date so that we can make alternative arrangements. Because you are given plenty of time to complete your work, and major due dates are given to you well in advance, last minute problems should not preclude handing in assignments on time.

------------------------------------------------------------------------

## Mandatory Reporter

Fitchburg State University is committed to providing a safe learning environment for all students that is free of all forms of discrimination and harassment. Please be aware all FSU faculty members are "mandatory reporters," which means that if you tell me about a situation involving sexual harassment, sexual assault, dating violence, domestic violence, or stalking, I am legally required to share that information with the Title IX Coordinator. If you or someone you know has been impacted by sexual harassment, sexual assault, dating or domestic violence, or stalking, FSU has staff members trained to support you. If you or someone you know has been impacted by sexual harassment, sexual assault, dating or domestic violence, or stalking, please visit <http://fitchburgstate.edu/titleix> to access information about university support and resources.

------------------------------------------------------------------------

## Health

[Health Services](http://www.google.com/url?q=http%3A%2F%2Fwww.fitchburgstate.edu%2Foffices-services-directory%2Fhealth-services%2F&sa=D&sntz=1&usg=AFQjCNEw5V0i0hL5DVO5b43gejNNaAt4ig)

Hours: Monday-Friday 8:30AM-5PM Location: Ground Level of Russell Towers (across from the entrance of Holmes Dining Hall) Phone: (978) 665-3643/3894

[Counseling Services](http://www.google.com/url?q=http%3A%2F%2Fwww.fitchburgstate.edu%2Foffices-services-directory%2Fcounseling-services%2F&sa=D&sntz=1&usg=AFQjCNEYiS4EmSvWerpp2bKr5lTpouPuqQ)

The Counseling Services Office offers a range of services including individual, couples and group counseling, crisis intervention, psychoeducational programming, outreach ALTERNATIVE ECOSYSTEMSs, and community referrals. Counseling services are confidential and are offered at no charge to all enrolled students. Staff at Counseling Services are also available for consultation to faculty, staff and students. Counseling Services is located in the Hammond, 3rd Floor, Room 317.

[Fitchburg Anti-Violence Education (FAVE)](http://www.google.com/url?q=http%3A%2F%2Fwww.fitchburgstate.edu%2Foffices-services-directory%2Ffitchburg-anti-violence-education%2F&sa=D&sntz=1&usg=AFQjCNFi5qy-wunMxX-hoWbA9YwT8aa4Ig)

FAVE collaborates with a number of community partners (e.g., YWCA Domestic Violence Services, Pathways for Change) to meet our training needs and to link survivors with community based resources. This site also features [resources](http://www.google.com/url?q=http%3A%2F%2Fwww.fitchburgstate.edu%2Foffices-services-directory%2Ffitchburg-anti-violence-education%2Ffitchburg-anti-violence-education-resources%2F&sa=D&sntz=1&usg=AFQjCNF9KZ2O1AvPMLJTHdNg1DfmYYtgog) for help or information about dating violence, domestic violence, sexual assault and stalking. If you or someone you know is in an abusive relationship or has been a victim of sexual assault, there are many places to go for help. Many can be accessed 24 hours a day, seven days a week, 365 days a year. On campus, free and confidential support is provided at both Counseling Services and Health Services.

*Community Food Pantry* Food insecurity is a growing issue and it certainly can affect student learning. The ability to have access to nutritious food is incredibly vital. The Falcon Bazaar, located in Hammond G 15, is stocked with food, basic necessities, and can provide meal swipes to support all Fitchburg State students experiencing food insecurity for a day or a semester.

The university continues to partner with Our Father's House to support student needs and access to food and services. All Fitchburg State University students are welcome at the Our Father's House Community Food Pantry. This Pantry is located at the Faith Christian Church at 40 Boutelle St., Fitchburg, MA and is open from 5-7pm. Each "household" may shop for nutritious food once per month by presenting a valid FSU ID.

------------------------------------------------------------------------

## Academic Integrity

The University "Academic Integrity" policy can be found online at [http:// www.fitchburgstate.edu/offices-services-directory/office-of-student-conductmediation-education/academic-integrity/.](http://www.fitchburgstate.edu/offices-services-directory/office-of-student-conduct-mediation-education/academic-integrity/) Students are expected to do their own work. Plagiarism and cheating are inexcusable. Any instance of plagiarism or cheating will automatically result in a zero on the assignment and may be reported the Office of Student and Academic Life at the discretion of the instructor.

Plagiarism includes, but is not limited to: - Using papers or work from another class. - Using another student's paper or work from any class. - Copying work or a paper from the Internet. - The egregious lack of citing sources or documenting research.

*If you're not clear on what is or is not plagiarism, ASK. The BEST case scenario if caught is a zero on that assignment, and ignorance of what does or does not count is not an excuse. That being said, I'm a strong supporter of* [*Fair Use*](https://en.wikipedia.org/wiki/Fair_Use) *doctrine. Just attribute what you use--and, again, ASK if there's any doubt.*

------------------------------------------------------------------------

## Americans With Disabilities Act (ADA)

If you need course adaptations or accommodations because of a disability, if you have emergency medical information to share with the instructor, or if you need special arrangements in case the building must be evacuated, please inform the faculty member as soon as possible.

------------------------------------------------------------------------

## Technology

At some point during the semester you will likely have a problem with technology. Your laptop will crash; your iPad battery will die; a recording you make will disappear; you will accidentally delete a file; the wireless will go down at a crucial time. These, however, are inevitabilities of life, not emergences. Technology problems are not excuses for unfinished or late work. Bad things may happen, but you can protect yourself by doing the following:

-   Plan ahead: A deadline is the last minute to turn in material. You can start---and finish---early, particularly if challenging resources are required, or you know it will be time consuming to finish this project.

-   Save work early and often: Think how much work you do in 10 minutes. I auto save every 2 minutes.

-   Make regular backups of files in a different location: Between Box, Google Drive, Dropbox, and iCloud, you have ample places to store and backup your materials. Use them.

-   Save drafts: When editing, set aside the original and work with a copy.

-   Practice safe computing: On your personal devices, install and use software to control viruses and malware.

------------------------------------------------------------------------

## Grading Policy

Grading for the course will follow the FSU grading policy below:

4.0: 95-100\
3.7: 92-94\
3.5: 89-91\
3.3: 86-88\
3.0: 83-85\
2.7: 80-82\
2.5: 77-79\
2.3: 74-76\
2.0: 71-73\
0.0: \< 70

------------------------------------------------------------------------

## Academic Resources

[Writing Center](http://www.fitchburgstate.edu/offices-services-directory/tutor-center/writing-help/)

[Academic Policies](http://catalog.fitchburgstate.edu/content.php?catoid=13&navoid=851)

[Disability Services](http://www.fitchburgstate.edu/offices-services-directory/disability-services/)

[Fitchburg State Alert system for emergencies, snow closures/delays, and faculty absences](https://www.getrave.com/login/fitchburgstate/)

[University Career Services](http://www.fitchburgstate.edu/offices-services-directory/career-counseling-and-advising/careerservices/)

------------------------------------------------------------------------
